### PR TITLE
Add support for PIM AAD Group eligibility

### PR DESCRIPTION
**Pull request by oWretch**
This PR provides support for Privileged Management of AAD Groups with Eligible assignments. This implements part of https://github.com/manicminer/hamilton/pull/248.

### CODE REVIEW

**Comment by oWretch** [comment]
As with #253, the tests use an environment variable with default in the test file to use a pre-existing PIM-enabled group.

**Comment by audunsolemdal** [comment]
Any chance for a review @manicminer ?

**Comment by oWretch** [comment]
A service principal can now activate the PIM groups. I've updated the tests to create the group, and they run successfully under the SP. It just needs to have the following Graph permissions:

PrivilegedAccess.ReadWrite.AzureADGroup
PrivilegedAssignmentSchedule.ReadWrite.AzureADGroup
PrivilegedEligibilitySchedule.ReadWrite.AzureADGroup
Test passes happily 🙂

```
=== RUN   TestPrivilegedAccessGroupEligibilityScheduleClient
--- PASS: TestPrivilegedAccessGroupEligibilityScheduleClient (18.44s)
PASS
ok  	github.com/manicminer/hamilton/msgraph	19.309s
```

**Comment by oWretch** [comment]
Replaced by #277

**Pull request closed without merging**
