### PR TITLE
Entitlement Management - AccessPackage Types

### PR DESCRIPTION
**Pull request by kaovd**
All API Related to main AccessPackages workflow within IG

#92

### CODE REVIEW

**Comment by manicminer** [comment]
Hi @kaovd, thanks for this PR!

The way you've implemented deletes for AccessPackageResourceRequests seems ok. It's arguable whether this should just be omitted and allowed to leak downstream but a thin wrapper like this seems reasonable to make it more appear more restful.

The asynchronous behavior when creating AccessPackageResourceRequests is a bit more challenging. For the initial delay, can we implement retries via a ConsistencyFailureFunc rather than a hard sleep? I haven't used this service before, but is [this](https://github.com/manicminer/hamilton/blob/f731fed6dd465932489980c733d03c180974984f/msgraph/accesspackageresourcerequest_test.go#L92) a reliable way to get the request ID? If so, could this potentially be implemented in the client so that the returned struct can be populated? If this were done, it might be wise to add a boolean argument to the method to toggle that particular step.

**Comment by kaovd** [comment]
The only way I've found to delete a resource is by getting its resource ID once the request has been made, as the Requests endpoint wont return the ID of the Resource it creates which while is a bit annoying - it is how the current documentation describes doing this 
https://docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&tabs=http
```
To remove an Azure AD app from a catalog, set the catalogId to be of the ID of the catalog, requestType to be AdminRemove, and the accessPackageResource the resource object to be removed. The resource object can be retrieved using list accessPackageResources.
```

For the flow of that endpoint downstream - on a Delete operation on the client would call the Pseduo-Get on the accessPackageResource to then be able to do the delete operation as seen in the Tests from the line you highlighted. Are you saying this could be rolled into the Create operation on the requests endpoint? While could simplify downstream could be a bit messy if so

Will move to a ConsistencyFailureFunc rather than a hard sleep

**Comment by manicminer** [comment]
> The only way I've found to delete a resource is by getting its resource ID once the request has been made, as the Requests endpoint wont return the ID of the Resource it creates which while is a bit annoying - it is how the current documentation describes doing this
> https://docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&tabs=http
> 
> ```
> To remove an Azure AD app from a catalog, set the catalogId to be of the ID of the catalog, requestType to be AdminRemove, and the accessPackageResource the resource object to be removed. The resource object can be retrieved using list accessPackageResources.
> ```

Cool, that's what I understood from your implementation 👍 

 
> For the flow of that endpoint downstream - on a Delete operation on the client would call the Pseduo-Get on the accessPackageResource to then be able to do the delete operation as seen in the Tests from the line you highlighted. Are you saying this could be rolled into the Create operation on the requests endpoint so we store it prehand? While could simplify downstream could be a bit messy if so
> 
> Will move to a ConsistencyFailureFunc rather than a hard sleep

Yeah that was my thinking. If you think this would be flaky or too messy we could not bother with it. We could gate it with a `pollForId` boolean on the Create method if you think consumers would sometimes rather skip this.

**Comment by kaovd** [comment]
Did consider this at first but thought it might've not been acceptable, but if your fine with it will see what i can do with it would simplify the workflow

**Comment by kaovd** [comment]
Think I'm mostly done in terms of raw implementation, pollForId bool works well. fixed bug in Policy Update

> $ go test -race ./msgraph -run="TestAccessPackage*"                                                                                                                                                                                                  [±feature/accessPackages ●]
ok      github.com/manicminer/hamilton/msgraph  15.021s

I haven't introduced a seperate _tests for the accesspackageresource endpoint as it gets covered within the accesspackageresourcerequest tests. Can do so if its needed.

**Comment by kaovd** [comment]
> $ go test -race ./msgraph -run="TestAccessPackage*"                                                                                                                                                [±feature/accessPackages ●●]
ok      github.com/manicminer/hamilton/msgraph  28.060s
  
Taking out of draft although probably a few things to review here but feel like I've got good test coverage - let me know

**Comment by manicminer** [comment]
@kaovd Thanks for your work on this! I unfortunately won't have time to review it today but will make sure it gets in to next week's release.

**Review by manicminer — APPROVED** [review]
@kaovd I've made some small changes to tidy up a little bit, and added some nil checks in the clients. Overall this LGTM, the tests seems sensible and are passing! Thanks again! 🚀

**Pull request merged**
