### PR TITLE
add support for app role assignments for users, groups and sp

### PR DESCRIPTION
**Pull request by michaljirman**
- Add support for app role assignments for users, groups and service principals
- Refactor existing app role assignments code to be used with all resource types (users, groups and service principals) while keeping resource type differences hidden
- Add app role assignments tests for users, groups and service principals

Supports app role assignments using the two available methods:
1. [appRoleAssignedTo relationship](https://docs.microsoft.com/en-us/graph/api/serviceprincipal-list-approleassignedto?view=graph-rest-1.0&tabs=http) 

    client example
    ```
    msgraph.NewServicePrincipalsClient(...)
    ```

2. [appRoleAssignments relationship](https://docs.microsoft.com/en-us/graph/api/user-list-approleassignments?view=graph-rest-1.0&tabs=http)

    client examples
    ``` 
    msgraph.NewGroupsAppRoleAssignmentsClient(...)
    msgraph.NewUsersAppRoleAssignmentsClient(...)
    msgraph.NewServicePrincipalsAppRoleAssignmentsClient(...) 
    ```

Related to this [issue](https://github.com/manicminer/hamilton/issues/36)

### CODE REVIEW

**Review by manicminer — COMMENTED** [review]
Thanks for looking at this @michaljirman.

I was thinking about app role assignments recently and wondered if it would make more sense to implement all of the functionality as part of the GroupsClient, ServicePrincipalsClient and UsersClient structs rather than having separate clients. WDYT?

**Comment by michaljirman** [comment]
@manicminer implementing method 2 within the GroupsClient, ServicePrincipalsClient and UsersClient will result in 3 near-identical methods in each of them and a lot of code duplication (appRoleAssignments relationship). We could still consider this refactor but it would be good to keep abstraction of these methods somewhere else and just call it from all of these clients. 

If we want to also keep method 1 we will additionally have extra 3 methods in the ServicePrincipalsClient (appRoleAssignedTo relationship)

**Comment by michaljirman** [comment]
@manicminer we should probably get this reviewed/updated before I forget what it does :-)

**Comment by manicminer** [comment]
@michaljirman Sorry for the delay in reviewing this, I've been focused on fixes and updates for the AzureAD Terraform provider the last 2 weeks. I'm planning to get this in along with #42 in the next few days.

**Review by manicminer — APPROVED** [review]
Thanks again @michaljirman, this LGTM  🚀

**Pull request merged**
